import { createContext, useContext, useState, useEffect } from 'react';

// Admin-panel UI strings. The customer-facing menu uses a separate table
// (src/i18n.js); this one only covers the /admin chrome. Russian is the
// default; English is kept as a switchable fallback.
export const adminStrings = {
  ru: {
    // login
    panel: 'Админ-панель',
    password: 'Пароль',
    wrongPassword: 'Неверный пароль',
    signIn: 'Войти',
    // header
    admin: 'Админ',
    viewMenu: 'Открыть меню',
    logout: 'Выйти',
    // tabs
    tabDishes: '☕ Напитки',
    tabCategories: '🏷 Категории',
    tabPromotions: '🔥 Акции',
    tabOrders: '🧾 Заказы',
    tabSettings: '⚙️ Настройки',
    tabQr: '🔳 QR',
    // common
    new: '+ Создать',
    edit: 'Изменить',
    del: 'Удал.',
    cancel: 'Отмена',
    save: 'Сохранить',
    saved: '✓ Сохранено',
    loading: 'Загрузка…',
    editTitle: 'Изменить',
    newTitle: 'Создать',
    // dishes
    drinks: 'Напитки',
    drink: 'напиток',
    confirmDeleteDrink: 'Удалить этот напиток?',
    hidden: 'скрыт',
    name: 'Название',
    description: 'Описание',
    ingredients: 'Ингредиенты (через запятую, по языкам)',
    priceAzn: 'Цена (AZN)',
    category: 'Категория',
    calories: 'Калории',
    weight: 'Вес (мл/г)',
    sizesOptional: 'Размеры (необязательно)',
    addSize: '+ Размер',
    noSizes: 'Без размеров — используется одна цена выше. Добавьте, например, S / M для коктейлей.',
    sizeLabelPh: 'Метка (S, M…)',
    sizeTip: 'Совет: держите поле «Цена (AZN)» равным наименьшему размеру — оно показывается на карточках и как запасное значение.',
    featured: 'Рекомендуемое ★',
    available: 'Доступно',
    photoOptional: 'Фото (необязательно)',
    removePhoto: 'Удалить фото',
    uploadHint: 'Нажмите, чтобы загрузить фото',
    uploadFormats: 'PNG, JPG — до 5 МБ',
    // categories
    categories: 'Категории',
    categoryWord: 'категория',
    confirmDeleteCategory: 'Удалить категорию?',
    sortOrder: 'Порядок',
    icon: 'Иконка',
    iconBuiltIn: 'Встроенная',
    iconCustom: 'Своя',
    uploadIcon: 'Загрузить иконку',
    // promotions
    promotions: 'Акции',
    promotionWord: 'акция',
    confirmDeletePromotion: 'Удалить акцию?',
    title: 'Заголовок',
    discount: 'Скидка %',
    // orders
    orders: 'Заказы',
    noOrders: 'Заказов пока нет.',
    fromQr: 'Из QR-кода',
    statusNew: 'Новый',
    statusPreparing: 'Готовится',
    statusReady: 'Готов',
    statusDone: 'Выдан',
    statusCancelled: 'Отменён',
    filterAll: 'Все',
    dateToday: 'Сегодня',
    dateYesterday: 'Вчера',
    dateMonth: 'Этот месяц',
    dateAll: 'Всё время',
    statOrders: 'Заказы',
    statRevenue: 'Выручка',
    statNew: 'Новые',
    statDelivered: 'Выдано',
    orderNo: 'Заказ',
    qrOrder: 'QR-заказ',
    cancelConfirm: 'Отменить этот заказ?',
    cancelYes: 'Да, отменить',
    cancelNo: 'Назад',
    newOrderToast: 'Новый заказ',
    table: 'Стол',
    btnAccept: 'Принять',
    btnCancel: 'Отменить',
    btnDeliver: 'Выдан',
    // settings
    settings: 'Настройки',
    cafeName: 'Название кофейни',
    phone: 'Телефон',
    instagram: 'Instagram',
    tiktok: 'TikTok',
    wifiName: 'Имя Wi-Fi',
    wifiPassword: 'Пароль Wi-Fi',
    address: 'Адрес',
    accentColor: 'Акцентный цвет',
    menuUrl: 'URL меню (для QR)',
    newAdminPassword: 'Новый пароль администратора',
    leaveBlank: 'оставьте пустым',
    whatsapp: 'Номер WhatsApp',
    whatsappHint: 'С кодом страны, напр. +994... — на него приходят заказы.',
    workingHours: 'Часы работы',
    hoursHint: 'Формат «08:00–22:00». Оставьте пустым — день не показывается.',
    saveSettings: 'Сохранить настройки',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    sunday: 'Воскресенье',
    // qr
    qrCode: 'QR-код',
    tableNumber: 'Номер стола (необязательно)',
    generate: 'Сгенерировать',
    download: 'Скачать',
    // cabinets
    tabCabinets: '🕹 Кабинеты',
    tabSets: '🍱 Сеты',
    open: 'Открыт',
    closed: 'Закрыт',
    openCabinet: 'Открыть',
    closeCabinet: 'Закрыть',
    elapsed: 'Прошло',
    runningCost: 'Текущая сумма',
    hourlyRate: 'Тариф в час',
    perHour: '/час',
    capacity: 'Вместимость',
    includesHookah: 'С кальяном',
    totalDue: 'Итого к оплате',
    confirmDeleteCabinet: 'Удалить этот кабинет?',
    uploading: 'Загрузка фото…',
  },
  en: {
    panel: 'Admin Panel',
    password: 'Password',
    wrongPassword: 'Wrong password',
    signIn: 'Sign in',
    admin: 'Admin',
    viewMenu: 'View menu',
    logout: 'Logout',
    tabDishes: '☕ Dishes',
    tabCategories: '🏷 Categories',
    tabPromotions: '🔥 Promotions',
    tabOrders: '🧾 Orders',
    tabSettings: '⚙️ Settings',
    tabQr: '🔳 QR',
    new: '+ New',
    edit: 'Edit',
    del: 'Del',
    cancel: 'Cancel',
    save: 'Save',
    saved: '✓ Saved',
    loading: 'Loading…',
    editTitle: 'Edit',
    newTitle: 'New',
    drinks: 'Drinks',
    drink: 'drink',
    confirmDeleteDrink: 'Delete this drink?',
    hidden: 'hidden',
    name: 'Name',
    description: 'Description',
    ingredients: 'Ingredients (comma list per lang)',
    priceAzn: 'Price (AZN)',
    category: 'Category',
    calories: 'Calories',
    weight: 'Weight (ml/g)',
    sizesOptional: 'Sizes (optional)',
    addSize: '+ Add size',
    noSizes: 'No sizes — the single price above is used. Add e.g. S / M for milkshakes.',
    sizeLabelPh: 'Label (S, M…)',
    sizeTip: 'Tip: keep the “Price (AZN)” field equal to the smallest size — it’s shown on cards and used as a fallback.',
    featured: 'Featured ★',
    available: 'Available',
    photoOptional: 'Photo (optional)',
    removePhoto: 'Remove photo',
    uploadHint: 'Click to upload a photo',
    uploadFormats: 'PNG, JPG — up to 5 MB',
    categories: 'Categories',
    categoryWord: 'category',
    confirmDeleteCategory: 'Delete category?',
    sortOrder: 'Sort order',
    icon: 'Icon',
    iconBuiltIn: 'Built-in',
    iconCustom: 'Custom',
    uploadIcon: 'Upload icon',
    promotions: 'Promotions',
    promotionWord: 'promotion',
    confirmDeletePromotion: 'Delete promotion?',
    title: 'Title',
    discount: 'Discount %',
    orders: 'Orders',
    noOrders: 'No orders yet.',
    fromQr: 'From QR code',
    statusNew: 'New',
    statusPreparing: 'Preparing',
    statusReady: 'Ready',
    statusDone: 'Done',
    statusCancelled: 'Cancelled',
    filterAll: 'All',
    dateToday: 'Today',
    dateYesterday: 'Yesterday',
    dateMonth: 'This month',
    dateAll: 'All time',
    statOrders: 'Orders',
    statRevenue: 'Revenue',
    statNew: 'New',
    statDelivered: 'Delivered',
    orderNo: 'Order',
    qrOrder: 'QR order',
    cancelConfirm: 'Cancel this order?',
    cancelYes: 'Yes, cancel',
    cancelNo: 'Go back',
    newOrderToast: 'New order',
    table: 'Table',
    btnAccept: 'Accept',
    btnCancel: 'Cancel',
    btnDeliver: 'Delivered',
    settings: 'Settings',
    cafeName: 'Café name',
    phone: 'Phone',
    instagram: 'Instagram',
    tiktok: 'TikTok',
    wifiName: 'Wi-Fi name',
    wifiPassword: 'Wi-Fi password',
    address: 'Address',
    accentColor: 'Accent color',
    menuUrl: 'Menu URL (for QR)',
    newAdminPassword: 'New admin password',
    leaveBlank: 'leave blank to keep',
    whatsapp: 'WhatsApp number',
    whatsappHint: 'Include country code, e.g. +994... — orders are sent here.',
    workingHours: 'Working hours',
    hoursHint: 'Format “08:00–22:00”. Leave blank to hide a day.',
    saveSettings: 'Save settings',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    qrCode: 'QR Code',
    tableNumber: 'Table number (optional)',
    generate: 'Generate',
    download: 'Download',
    // cabinets
    tabCabinets: '🕹 Cabinets',
    tabSets: '🍱 Sets',
    open: 'Open',
    closed: 'Closed',
    openCabinet: 'Open',
    closeCabinet: 'Close',
    elapsed: 'Elapsed',
    runningCost: 'Running cost',
    hourlyRate: 'Hourly rate',
    perHour: '/hour',
    capacity: 'Capacity',
    includesHookah: 'Includes hookah',
    totalDue: 'Total due',
    confirmDeleteCabinet: 'Delete this cabinet?',
    uploading: 'Uploading photo…',
  },
  az: {
    panel: 'Admin panel',
    password: 'Şifrə',
    wrongPassword: 'Yanlış şifrə',
    signIn: 'Daxil ol',
    admin: 'Admin',
    viewMenu: 'Menyunu aç',
    logout: 'Çıxış',
    tabDishes: '☕ İçkilər',
    tabCategories: '🏷 Kateqoriyalar',
    tabPromotions: '🔥 Aksiyalar',
    tabOrders: '🧾 Sifarişlər',
    tabSettings: '⚙️ Parametrlər',
    tabQr: '🔳 QR',
    new: '+ Yarat',
    edit: 'Dəyiş',
    del: 'Sil',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    saved: '✓ Saxlanıldı',
    loading: 'Yüklənir…',
    editTitle: 'Dəyiş',
    newTitle: 'Yarat',
    drinks: 'İçkilər',
    drink: 'içki',
    confirmDeleteDrink: 'Bu içkini silmək?',
    hidden: 'gizli',
    name: 'Ad',
    description: 'Təsvir',
    ingredients: 'Tərkib (vergüllə, dillər üzrə)',
    priceAzn: 'Qiymət (AZN)',
    category: 'Kateqoriya',
    calories: 'Kalori',
    weight: 'Çəki (ml/q)',
    sizesOptional: 'Ölçülər (istəyə görə)',
    addSize: '+ Ölçü',
    noSizes: 'Ölçü yoxdur — yuxarıdakı tək qiymət istifadə olunur. Məsələn, kokteyllər üçün S / M əlavə edin.',
    sizeLabelPh: 'Etiket (S, M…)',
    sizeTip: 'Məsləhət: «Qiymət (AZN)» sahəsini ən kiçik ölçüyə bərabər saxlayın — o, kartlarda göstərilir və ehtiyat dəyər kimi istifadə olunur.',
    featured: 'Seçilmiş ★',
    available: 'Mövcuddur',
    photoOptional: 'Şəkil (istəyə görə)',
    removePhoto: 'Şəkli sil',
    uploadHint: 'Şəkil yükləmək üçün klikləyin',
    uploadFormats: 'PNG, JPG — 5 MB-a qədər',
    categories: 'Kateqoriyalar',
    categoryWord: 'kateqoriya',
    confirmDeleteCategory: 'Kateqoriyanı silmək?',
    sortOrder: 'Sıra',
    icon: 'İkon',
    iconBuiltIn: 'Daxili',
    iconCustom: 'Öz',
    uploadIcon: 'İkon yüklə',
    promotions: 'Aksiyalar',
    promotionWord: 'aksiya',
    confirmDeletePromotion: 'Aksiyanı silmək?',
    title: 'Başlıq',
    discount: 'Endirim %',
    orders: 'Sifarişlər',
    noOrders: 'Hələ sifariş yoxdur.',
    fromQr: 'QR koddan',
    statusNew: 'Yeni',
    statusPreparing: 'Hazırlanır',
    statusReady: 'Hazır',
    statusDone: 'Verildi',
    statusCancelled: 'Ləğv edildi',
    filterAll: 'Hamısı',
    dateToday: 'Bugün',
    dateYesterday: 'Dünən',
    dateMonth: 'Bu ay',
    dateAll: 'Bütün vaxt',
    statOrders: 'Sifariş',
    statRevenue: 'Gəlir',
    statNew: 'Yeni',
    statDelivered: 'Verildi',
    orderNo: 'Sifariş',
    qrOrder: 'QR sifariş',
    cancelConfirm: 'Bu sifarişi ləğv etmək istəyirsiniz?',
    cancelYes: 'Bəli, ləğv et',
    cancelNo: 'Geri qayıt',
    newOrderToast: 'Yeni sifariş gəldi',
    table: 'Masa',
    btnAccept: 'Qəbul et',
    btnCancel: 'Ləğv et',
    btnDeliver: 'Verildi',
    settings: 'Parametrlər',
    cafeName: 'Kafe adı',
    phone: 'Telefon',
    instagram: 'Instagram',
    tiktok: 'TikTok',
    wifiName: 'Wi-Fi adı',
    wifiPassword: 'Wi-Fi şifrəsi',
    address: 'Ünvan',
    accentColor: 'Vurğu rəngi',
    menuUrl: 'Menyu URL (QR üçün)',
    newAdminPassword: 'Yeni admin şifrəsi',
    leaveBlank: 'dəyişməmək üçün boş buraxın',
    whatsapp: 'WhatsApp nömrəsi',
    whatsappHint: 'Ölkə kodu ilə, məs. +994... — sifarişlər buraya gəlir.',
    workingHours: 'İş saatları',
    hoursHint: 'Format «08:00–22:00». Boş buraxsanız gün göstərilmir.',
    saveSettings: 'Parametrləri saxla',
    monday: 'Bazar ertəsi',
    tuesday: 'Çərşənbə axşamı',
    wednesday: 'Çərşənbə',
    thursday: 'Cümə axşamı',
    friday: 'Cümə',
    saturday: 'Şənbə',
    sunday: 'Bazar',
    qrCode: 'QR kod',
    tableNumber: 'Masa nömrəsi (istəyə görə)',
    generate: 'Yarat',
    download: 'Yüklə',
    // cabinets
    tabCabinets: '🕹 Kabinetlər',
    tabSets: '🍱 Setlər',
    open: 'Açıq',
    closed: 'Bağlı',
    openCabinet: 'Aç',
    closeCabinet: 'Bağla',
    elapsed: 'Keçən vaxt',
    runningCost: 'Cari məbləğ',
    hourlyRate: 'Saatlıq tarif',
    perHour: '/saat',
    capacity: 'Tutum',
    includesHookah: 'Qəlyan daxil',
    totalDue: 'Cəmi ödəniş',
    confirmDeleteCabinet: 'Bu kabineti silmək?',
    uploading: 'Şəkil yüklənir…',
  },
  tr: {
    panel: 'Yönetim Paneli',
    password: 'Şifre',
    wrongPassword: 'Yanlış şifre',
    signIn: 'Giriş yap',
    admin: 'Yönetim',
    viewMenu: 'Menüyü aç',
    logout: 'Çıkış',
    tabDishes: '☕ İçecekler',
    tabCategories: '🏷 Kategoriler',
    tabPromotions: '🔥 Kampanyalar',
    tabOrders: '🧾 Siparişler',
    tabSettings: '⚙️ Ayarlar',
    tabQr: '🔳 QR',
    new: '+ Oluştur',
    edit: 'Düzenle',
    del: 'Sil',
    cancel: 'İptal',
    save: 'Kaydet',
    saved: '✓ Kaydedildi',
    loading: 'Yükleniyor…',
    editTitle: 'Düzenle',
    newTitle: 'Oluştur',
    drinks: 'İçecekler',
    drink: 'içecek',
    confirmDeleteDrink: 'Bu içecek silinsin mi?',
    hidden: 'gizli',
    name: 'Ad',
    description: 'Açıklama',
    ingredients: 'İçindekiler (virgülle, dile göre)',
    priceAzn: 'Fiyat (AZN)',
    category: 'Kategori',
    calories: 'Kalori',
    weight: 'Ağırlık (ml/g)',
    sizesOptional: 'Boyutlar (isteğe bağlı)',
    addSize: '+ Boyut',
    noSizes: 'Boyut yok — yukarıdaki tek fiyat kullanılır. Örneğin milkshake için S / M ekleyin.',
    sizeLabelPh: 'Etiket (S, M…)',
    sizeTip: 'İpucu: «Fiyat (AZN)» alanını en küçük boyuta eşit tutun — kartlarda gösterilir ve yedek değer olarak kullanılır.',
    featured: 'Öne çıkan ★',
    available: 'Mevcut',
    photoOptional: 'Fotoğraf (isteğe bağlı)',
    removePhoto: 'Fotoğrafı kaldır',
    uploadHint: 'Fotoğraf yüklemek için tıklayın',
    uploadFormats: 'PNG, JPG — 5 MB’a kadar',
    categories: 'Kategoriler',
    categoryWord: 'kategori',
    confirmDeleteCategory: 'Kategori silinsin mi?',
    sortOrder: 'Sıra',
    icon: 'Simge',
    iconBuiltIn: 'Yerleşik',
    iconCustom: 'Özel',
    uploadIcon: 'Simge yükle',
    promotions: 'Kampanyalar',
    promotionWord: 'kampanya',
    confirmDeletePromotion: 'Kampanya silinsin mi?',
    title: 'Başlık',
    discount: 'İndirim %',
    orders: 'Siparişler',
    noOrders: 'Henüz sipariş yok.',
    fromQr: 'QR kodundan',
    statusNew: 'Yeni',
    statusPreparing: 'Hazırlanıyor',
    statusReady: 'Hazır',
    statusDone: 'Teslim edildi',
    statusCancelled: 'İptal edildi',
    filterAll: 'Tümü',
    dateToday: 'Bugün',
    dateYesterday: 'Dün',
    dateMonth: 'Bu ay',
    dateAll: 'Tüm zamanlar',
    statOrders: 'Sipariş',
    statRevenue: 'Gelir',
    statNew: 'Yeni',
    statDelivered: 'Teslim edildi',
    orderNo: 'Sipariş',
    qrOrder: 'QR sipariş',
    cancelConfirm: 'Bu siparişi iptal etmek istiyor musunuz?',
    cancelYes: 'Evet, iptal et',
    cancelNo: 'Geri dön',
    newOrderToast: 'Yeni sipariş geldi',
    table: 'Masa',
    btnAccept: 'Kabul et',
    btnCancel: 'İptal et',
    btnDeliver: 'Teslim edildi',
    settings: 'Ayarlar',
    cafeName: 'Kafe adı',
    phone: 'Telefon',
    instagram: 'Instagram',
    tiktok: 'TikTok',
    wifiName: 'Wi-Fi adı',
    wifiPassword: 'Wi-Fi şifresi',
    address: 'Adres',
    accentColor: 'Vurgu rengi',
    menuUrl: 'Menü URL (QR için)',
    newAdminPassword: 'Yeni yönetici şifresi',
    leaveBlank: 'değiştirmemek için boş bırakın',
    whatsapp: 'WhatsApp numarası',
    whatsappHint: 'Ülke koduyla, örn. +994... — siparişler buraya gelir.',
    workingHours: 'Çalışma saatleri',
    hoursHint: 'Format “08:00–22:00”. Boş bırakırsanız gün gösterilmez.',
    saveSettings: 'Ayarları kaydet',
    monday: 'Pazartesi',
    tuesday: 'Salı',
    wednesday: 'Çarşamba',
    thursday: 'Perşembe',
    friday: 'Cuma',
    saturday: 'Cumartesi',
    sunday: 'Pazar',
    qrCode: 'QR Kodu',
    tableNumber: 'Masa numarası (isteğe bağlı)',
    generate: 'Oluştur',
    download: 'İndir',
    // cabinets
    tabCabinets: '🕹 Kabinler',
    tabSets: '🍱 Setler',
    open: 'Açık',
    closed: 'Kapalı',
    openCabinet: 'Aç',
    closeCabinet: 'Kapat',
    elapsed: 'Geçen süre',
    runningCost: 'Güncel tutar',
    hourlyRate: 'Saatlik ücret',
    perHour: '/saat',
    capacity: 'Kapasite',
    includesHookah: 'Nargile dahil',
    totalDue: 'Ödenecek toplam',
    confirmDeleteCabinet: 'Bu kabin silinsin mi?',
    uploading: 'Fotoğraf yükleniyor…',
  },
};

// Languages the admin chrome can be displayed in (order = cycle order in the
// header switcher). Matches the customer-facing LANGUAGES set in i18n.js.
export const ADMIN_LANG_CODES = Object.keys(adminStrings);

const AdminLangContext = createContext({ lang: 'ru', setLang: () => {}, t: adminStrings.ru });

export function AdminLangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('admin_lang') || 'ru');
  useEffect(() => { localStorage.setItem('admin_lang', lang); }, [lang]);
  const value = { lang, setLang, t: adminStrings[lang] || adminStrings.ru };
  return <AdminLangContext.Provider value={value}>{children}</AdminLangContext.Provider>;
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
